=== AnarchI-Technologies-MAIN/AnarchI-Brain/schemas/root/proposal.v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "serialization_profile",
    "schema_id",
    "schema_version",
    "proposal"
  ],
  "properties": {
    "serialization_profile": {
      "type": "string",
      "const": "ACS-1"
    },
    "schema_id": {
      "type": "string",
      "const": "anarchi.brain.proposal"
    },
    "schema_version": {
      "type": "string",
      "const": "1"
    },
    "proposal": {
      "type": [
        "object",
        "array",
        "string",
        "integer",
        "boolean"
      ]
    }
  },
  "additionalProperties": false
}

=== AnarchI-Technologies-MAIN/AnarchI-Brain/qualification/ingress-review-unit-a-v1.2/fixture_first_brain.json
{"proposal":{"adapter_profile":"EPI-CORTEX-OFFLINE-PROPOSAL-DRAFT-5","admission_state":"NONCANONICAL_CANDIDATE","attachment_resolution":"PINNED_SOURCE_DATABASE_ONLY_NO_AUTOEXECUTION","authority_resolution":"UNRESOLVED","canonical_membership":false,"database_sha256":"b849752058715104ab8b17396c0f7b1ec5884d7c63aea4ecd876e0ccb239c9cf","epistemaddy_proposal_sha256":"ce2042084b61b562dcc5cb750365579a25ab48d4475c7deec562889f296b8763","epistemaddy_proposal_utf8_base64":"eyJjb250ZW50Ijp7ImFkYXB0ZXJfcHJvZmlsZSI6IkVQSS1DT1JURVgtT0ZGTElORS1QUk9QT1NBTC1EUkFGVC01IiwiYWRtaXNzaW9uX3N0YXRlIjoiTk9OQ0FOT05JQ0FMX0NBTkRJREFURSIsImF0dGFjaG1lbnRfcmVzb2x1dGlvbiI6IlBJTk5FRF9TT1VSQ0VfREFUQUJBU0VfT05MWV9OT19BVVRPRVhFQ1VUSU9OIiwiYXV0aG9yaXR5X3Jlc29sdXRpb24iOiJVTlJFU09MVkVEIiwiY2Fub25pY2FsX21lbWJlcnNoaXAiOmZhbHNlLCJkYXRhYmFzZV9zaGEyNTYiOiJiODQ5NzUyMDU4NzE1MTA0YWI4YjE3Mzk2YzBmN2IxZWM1ODg0ZDdjNjNhZWE0ZWNkODc2ZTBjY2IyMzljOWNmIiwiZ292ZXJuaW5nX2Jhc2VsaW5lX2Fkb3B0ZWQiOmZhbHNlLCJwcm9kdWNlcl9wcm92ZW5hbmNlIjp7ImZpbGVzIjp7IkVQSVNURU1BRERZX01BSU5fQ09OVFJBQ1QubWQiOnsiY2hlY2tvdXRfc2hhMjU2IjoiMTQ5ZWI1NTcyMjdmNDg4Y2I5ODQyNmI4NDAyZGE4YTY0NDhjMWU3MjYxOTBiOTg5MmI2MDdiYjBiYWExODljZSIsImdpdF9ibG9iX29pZCI6IjlkM2RkZjIxNjc3MmUyY2M4ZDAwN2E3YzA1OWUzOGY2MjY2NjQ4MGUiLCJnaXRfYmxvYl9zaGEyNTYiOiJkYzMxYmY1NGYzOTk3OGU0ZTY2MWFkY2VmNzNlYjNiYjQyMTNkYTg0MjJlNmRhM2YxNjM1YWI4OGUzMDYyYWE1IiwicmVwcmVzZW50YXRpb25fbWFwcGluZyI6IkNSTEZfVE9fTEZfRVhBQ1RfQ09NUEFSSVNPTiJ9LCJKVU5DVElPTl9DT05UUkFDVC5tZCI6eyJjaGVja291dF9zaGEyNTYiOiI4MmI1MTE0NGQ4ZDYxZjk1YjE1YmUyNDFiNDljNjBhOTA0ZmM2Y2MxZDVhZGQ3ZDQwNDQzYjczMTQ5MjYxZTUyIiwiZ2l0X2Jsb2Jfb2lkIjoiZWI2N2FkNjM4YzZjYzVjZGI1ZWQ0MmU4NjY3ODI4Y2Q4MDU0YmM0ZiIsImdpdF9ibG9iX3NoYTI1NiI6ImI0OWUwYjVjODY3ZjJkYjdiMjMwZmEzYzNiMmZjOWU2YmVlZjE3NGRiNmMzNTQ2NDNjZjFiYzNiNDg4MTc5MzAiLCJyZXByZXNlbnRhdGlvbl9tYXBwaW5nIjoiQ1JMRl9UT19MRl9FWEFDVF9DT01QQVJJU09OIn0sImNvcmUvc3RhdGVzL3N0YXRlX21vZGVsLnB5Ijp7ImNoZWNrb3V0X3NoYTI1NiI6IjRhYzUxNmFlZTU2MjM0YTU3MTk4YjJjNmE2YjY0MzMwODk4ZTY1YmJkMzA5ZmEzYTkwYWIyYjRjZmFlOWIzZjgiLCJnaXRfYmxvYl9vaWQiOiI5ZGI5MzdhMmZmMTA4YWZlNjJhNmU4YzQ1NGRlOWI5NDcyZGE2YjQ4IiwiZ2l0X2Jsb2Jfc2hhMjU2IjoiZDQ1ZWI0OGVlY2IxNDQxZWEzMTk0ZDQ4MDI2NTY0NDkxNDk5YTkwZDcxOTg1ZGFkODExZDYwZWU3M2ZkZThiYyIsInJlcHJlc2VudGF0aW9uX21hcHBpbmciOiJDUkxGX1RPX0xGX0VYQUNUX0NPTVBBUklTT04ifSwiY29yZS92ZXJ0aWNhbF9zbGljZS5weSI6eyJjaGVja291dF9zaGEyNTYiOiJmN2RjZTRhNWRmNTc2NWMzNDc5OTc5OWNjMGZjNTBiZDI0YTA5ODhiZGQyODk4OGUwYTQ2NzRkYjZlYzg2MWNiIiwiZ2l0X2Jsb2Jfb2lkIjoiOTE4NDg5MTVhZjNlMjk3YzEwYzViMjI3MzAyZDBkMDJiM2JkZmFlMCIsImdpdF9ibG9iX3NoYTI1NiI6IjZkY2NhYmMyMjQ2MmEwNzhmZDUxZjVmYjRmODg4MWQ4Y2RjNjczMmJjZjAxMTAwZGU0YzQ4ZTVjN2VmOWY0OTUiLCJyZXByZXNlbnRhdGlvbl9tYXBwaW5nIjoiQ1JMRl9UT19MRl9FWEFDVF9DT01QQVJJU09OIn19LCJyZXBvc2l0b3J5X2hlYWQiOiI2NWRiMzZiNWY1MWY1OGVlYzAzOGU1ZmQ2ODQ0ZDRjZGNiOGNlMGExIiwic2NvcGUiOiJTRUxFQ1RFRF9TT1VSQ0VfQU5DRVNUUllfTk9UX1dIT0xFX1JFUE9TSVRPUllfQ0xFQU5MSU5FU1MifSwicHVycG9zZSI6Im5vbmNhbm9uaWNhbC5vZmZsaW5lLmNhbmRpZGF0ZS1yZXZpZXciLCJyZXF1aXJlZF9jeWNsZSI6IlZBTElEQVRJT05fUVVBTElGSUNBVElPTl9USFJFRV9JTkRFUEVOREVOVF9DQU5PTklDQUxfQURKVURJQ0FUSU9OU19HVUFSREVEX0NPTU1JVCIsInNvdXJjZV9hdXRoZW50aWNpdHkiOiJVTlNJR05FRCIsInNvdXJjZV9jYW5kaWRhdGVfaWQiOiJFUEktQ0FOLTAwMDEiLCJzb3VyY2VfZXhhY3RfcmVjb3JkX3NoYTI1NiI6IjE3Mzc2YjZhYjI0MzUyMDE0MWM0MmRkM2ZmYjUyODViYzBjZmIwYTk2MDhiZDdiMjNiZTNkNDc2MDA2Njg4ODgiLCJzb3VyY2Vfbm9ybWFsaXphdGlvbl9wcm9maWxlIjoiZXBpc3RlbWFkZHktcHl0aG9uLWpzb24tdjEtbm90LVJGQzg3ODUiLCJzb3VyY2Vfbm9ybWFsaXplZF9yZWNvcmRfc2hhMjU2IjoiZTU4MTliOTNhNGM3NTAyMjAxYjU5MGRhNTljNjZmYzk2YTE3NjM1MjgwZTUyNjMzYjZkMGIxYWE2OTQ2ZTgxMiIsInNvdXJjZV9wYWNrYWdlX2lkIjoiZXBpc3RlbWFkZHktYXRsYXMtdjMuMS1pbmdlc3QtMjAyNjEwMDMiLCJzb3VyY2VfcmVjb3JkX3V0ZjhfYmFzZTY0IjoiZXlKallXNWthV1JoZEdWZmFXUWlPaUFpUlZCSkxVTkJUaTB3TURBeElpd2dJbU52Ykd4bFkzUnBiMjRpT2lBaVJYQnBjM1JsYldsaklFTmhibTl1SUVOaGJtUmhaR2wwWlhNdFFXUnFkV1JwWTJGMGFXOXVJRkJ5YjJObGMzTWdRbTkxYm1RdFZXNVFjbTkyWlc0Z1lua2dVM1ZpYzNSeVlYUmxJaXdnSW01aGJXVWlPaUFpVkdGemF5MXpZMjl3WlNCdFlXNXBabVZ6ZENJc0lDSm1ZVzFwYkhsZmFXUWlPaUFpUmpBeElpd2dJbVpoYldsc2VTSTZJQ0pEYjIxdFlXNWtJR0Z1WkNCelkyOXdaU0JqYjI1MGNtRmpkSE1pTENBaVltOTFibVJoY25sZmRIbHdaU0k2SUNKaGRYUm9iM0pwZW1Wa0lIUmhjMnNnYzJOdmNHVWlMQ0FpY21Wa2RXTjBhVzl1WDJoNWNHOTBhR1Z6YVhNaU9pQWlVbVZrZFdObElISmxZMjl1YzJsa1pYSmhkR2x2YmlCdlppQmhiSEpsWVdSNUlHRjFkR2h2Y21sNlpXUWdjMk52Y0dVc0lISnZiR1Z6SUdGdVpDQmhZMk5sY0hSaGJtTmxJR0p2ZFc1a1lYSnBaWE11SWl3Z0luQnlhVzVqYVhCaGJGOXlhWE5ySWpvZ0lrRWdaR1ZqYkdGeVpXUWdjMk52Y0dVZ1kyRnVJRzl0YVhRZ2MyOXRaWFJvYVc1bklIUm9aU0IwWVhOcklHRmpkSFZoYkd4NUlISmxjWFZwY21WekxpSXNJQ0pqYjI1emRISjFZM1JwYjI1ZmNtVnhkV2x5WlhNaU9pQWlWWE5sY2lCdmNpQmhkWFJvYjNKcGVtVmtJR1ZrYVhSdmNpQmtaV1pwYm1WeklIUm9aU0JqYjI1MGNtRmpkRHNnWVNCdGIyUmxiQ0J0WVhrZ1pISmhablFnWW5WMElHMWhlU0J1YjNRZ2MyVnNaaTFoZFhSb2IzSnBlbVVnYVhRdUlpd2dJbVYyYVdSbGJtTmxYMkpoYzJseklqb2dJbkJ5YjNCdmMyVmtYM0J5YjJObGMzTmZjR0YwZEdWeWJpSXNJQ0p2WW1wbFkzUmZhMmx1WkNJNklDSmtaWE5qY21sd2RHbDJaVjlqWVc1a2FXUmhkR1ZmZDNKaGNIQmxjaUlzSUNKd1lYbHNiMkZrSWpvZ0lsUmhjMnNnU1VRc0lHUmxiR2wyWlhKaFlteGxMQ0JwYmkxelkyOXdaU0JsYm5ScGRHbGxjeXdnWlhod2JHbGphWFFnWlhoamJIVnphVzl1Y3k0aUxDQWlZMjl1WkdsMGFXOXVZV3hmWjNWaGNtRnVkR1ZsSWpvZ0lrRWdZMmhsWTJ0bGNpQmpZVzRnY21WcVpXTjBJR0ZqWTJWemMyVnpJRzkxZEhOcFpHVWdZVzRnWlc1MWJXVnlZWFJsWkNCelkyOXdaUzRpTENBaVlYTnpkVzF3ZEdsdmJuTmZZVzVrWDJ4cGJXbDBjeUk2SUNKRmJuVnRaWEpoZEdsdmJpQnBjeUJoSUhCdmJHbGplU0JpYjNWdVpHRnllU3dnYm05MElIQnliMjltSUc5bUlITmxiV0Z1ZEdsaklITjFabVpwWTJsbGJtTjVMaUlzSUNKemFXUmxZMkZ5WDJOb1pXTnJJam9nSWsxaGRHTm9JSEpsY1hWbGMzUmxaQ0JsYm5ScGRHbGxjeUJoYm1RZ1lXTmpaWE56WlhNZ2RHOGdkR2hsSUcxaGJtbG1aWE4wTGlJc0lDSnBiblpoYkdsa1lYUnBiMjVmZEhKcFoyZGxjaUk2SUNKVVlYTnJJRzl5SUdGMWRHaHZjbWw2WldRZ2MyTnZjR1VnWTJoaGJtZGxjeTRpTENBaVlteHZaMmRwYm1kZlpYaGhiWEJzWlNJNklDSk1hVzFwZENCaElIQnZjM1FnZEc4Z2IyNWxJSEJ5YjJSMVkzUWdZVzVrSUhOMWNIQnNhV1ZrSUhKbGJHVmhjMlVnYm05MFpYTXVJaXdnSW1OdlpHbHVaMTlsZUdGdGNHeGxJam9nSWt4cGJXbDBJR0VnY0dGMFkyZ2dkRzhnZEdobElHNWhiV1ZrSUcxdlpIVnNaU0JoYm1RZ1ltVm9ZWFpwYjNJdUlpd2dJbk52ZFhKalpWOXBaSE1pT2lCYklsSXhNQ0lzSUNKU01UWWlYU3dnSW5OdmRYSmpaVjkxY214eklqb2dXeUpvZEhSd2N6b3ZMMlJ2YVM1dmNtY3ZNVEF1TVRFd09TOVFVazlETGpFNU56VXVPVGt6T1NJc0lDSm9kSFJ3Y3pvdkwzZDNkeTV5Wm1NdFpXUnBkRzl5TG05eVp5OXlabU12Y21aak1qRXhPU0pkTENBaWMyOTFjbU5sWDNKbGJHRjBhVzl1SWpvZ0lrSmhZMnRuY205MWJtUWdZVzVoYkc5bmVTQnZjaUJ0WldOb1lXNXBjMjBnYjI1c2VUc2dibThnY0hKdmIyWWdiMllnZEdocGN5QndjbTl3YjNObFpDQndZWFIwWlhKdUxpSXNJQ0poWkdwMVpHbGpZWFJwYjI1ZmMzUmhkSFZ6SWpvZ0ltTmhibVJwWkdGMFpWOXdaVzVrYVc1blgyRmthblZrYVdOaGRHbHZiaUlzSUNKemRXSnpkSEpoZEdWZmMzUmhkSFZ6SWpvZ0luVnVjSEp2ZG1WdVgyNXZkRjkwWlhOMFpXUWlMQ0FpYVcxd2JHVnRaVzUwWVhScGIyNWZjM1JoZEhWeklqb2dJbTV2ZEY5cGJYQnNaVzFsYm5SbFpDSXNJQ0ptYjNKdFlXeGZZMlZ5ZEdsbWFXTmhkR1ZmYzNSaGRIVnpJam9nSW01dmRGOXpkWEJ3YkdsbFpDSXNJQ0p0YjJSbGJGOWxabVpwWTJsbGJtTjVYM04wWVhSMWN5STZJQ0pvZVhCdmRHaGxjMmx6WDI5dWJIa2lMQ0FpYjJKelpYSjJaV1JmY21WemRXeDBjeUk2SUc1MWJHd3NJQ0pvZFcxaGJsOXlaWFpwWlhkbGNpSTZJRzUxYkd3c0lDSnlaWFpwWlhkbFpGOWhkQ0k2SUc1MWJHd3NJQ0p6YjNWeVkyVmZkbVZ5YVdacFkyRjBhVzl1WDNOMFlYUjFjeUk2SUNKaWFXSnNhVzluY21Gd2FHbGpYM04wWVhKMGFXNW5YM0J2YVc1MFgyNXZkRjlzYVhabFgzWmxjbWxtYVdWa0lpd2dJbUYxZEdodmNtbDBlVjl5ZFd4bElqb2dJazl1YkhrZ2RYTmxjaTFoZFhSb2IzSnBlbVZrSUhOamIzQmxJR0Z1WkNCaGNIQnNhV05oWW14bElHaHBaMmhsY2kxd2NtbHZjbWwwZVNCd2IyeHBZM2tnYldGNUlITmxkQ0JpYjNWdVpHRnlhV1Z6T3lCemIzVnlZMlVnWTI5dWRHVnVkQ0JqWVc1dWIzUWdaM0poYm5RZ1lYVjBhRzl5YVhSNUxpSXNJQ0ptWVdsc2RYSmxYMkZqZEdsdmJpSTZJQ0pTWlhSMWNtNGdUa1ZGUkZOZlUwTlBVRVZmVWtWV1NVVlhJSGRwZEdnZ2RHaGxJR1poYVd4bFpDQmpiMjVrYVhScGIyNDdJSEpsZEdGcGJpQjBhR1VnYldsemMybHVaeUJrWlhCbGJtUmxibU41TGlCRWJ5QnViM1FnYzJsc1pXNTBiSGtnZDJsa1pXNGdZWFYwYUc5eWFYUjVJRzl5SUhSeVpXRjBJRzFwYzNOcGJtY2daWFpwWkdWdVkyVWdZWE1nWm1Gc2MyVXVJaXdnSW01dmJsOWpiMmR1YVhScGIyNWZiR2x0YVhRaU9pQWlWbUZzYVdSaGRHVXNJSE5sYkdWamRDQmllU0JsZUhCc2FXTnBkQ0J5ZFd4bExDQnZjaUIzYVhSb2FHOXNaQ0JoYmlCaGNuUnBabUZqZERzZ1pHOGdibTkwSUdOb2IyOXpaU0JuYjJGc2N5d2dhVzUyWlc1MElIQnlaVzFwYzJWekxDQnBibVpsY2lCaElHWnBibUZzSUdGdWMzZGxjaXdnYjNJZ1lXUnFkV1JwWTJGMFpTQnpaVzFoYm5ScFl5QjBjblYwYUM0aUxDQWlaWFpoYkhWaGRHbHZibDl3Y205MGIyTnZiRjlwWkNJNklDSkZVRWt0UlZaQlRDMHdNU0lzSUNKd2NtbHZjbWwwZVNJNklDSnpkR0Z5ZEdWeVgzSmxkbWxsZHlJc0lDSmpjbVZoZEdWa1gyUmhkR1VpT2lBaU1qQXlOaTB4TUMwd01TSXNJQ0pqWVc1dmJtbGpZV3hmYm1GdFpWOXpkR0YwZFhNaU9pQWlkMjl5YTJsdVoxOXNZV0psYkY5dWIzUmZZMnhoYVcxbFpGOWhjMTl3ZFdKc2FYTm9aV1JmZEdWeWJTSXNJQ0ppWlc1bFptbDBYMlYyYVdSbGJtTmxJam9nSWs1dklHMXZaR1ZzSUc5eUlIQnliMlIxWTNScGIyNGdkMjl5YTJac2IzY2dZbVZ1WTJodFlYSnJPeUJ1YnlCdFpXRnpkWEpsWkNCeVpYTnZkWEpqWlNCellYWnBibWR6TGlJc0lDSmhaR3AxWkdsallYUnBiMjVmY1hWbGMzUnBiMjV6SWpvZ1d5SkViMlZ6SUhSb1pTQnlaWEYxWlhOMFpXUWdkR0Z6YXlCaGRYUm9iM0pwZW1VZ2RHaHBjeUJpYjNWdVpHRnllVDhpTENBaVJHOWxjeUIwYUdVZ1kybDBaV1FnWW1GemFYTWdZV04wZFdGc2JIa2djM1Z3Y0c5eWRDQjBhR1VnWlhoaFkzUWdZMjl1WkdsMGFXOXVZV3dnWjNWaGNtRnVkR1ZsUHlJc0lDSkJjbVVnWVd4c0lHMWhkR1Z5YVdGc0lHRnpjM1Z0Y0hScGIyNXpJR1Y0Y0d4cFkybDBJR0Z1WkNCcWRYTjBhV1pwWldRL0lpd2dJa2x6SUhSb1pYSmxJR0VnWTJWeWRHbG1hV05oZEdVZ2IzSWdaVzVtYjNKalpXRmliR1VnY25Wc1pTd2dZVzVrSUdseklHbDBJR0p2ZFc1a0lIUnZJSFJvWlNCeWFXZG9kQ0JoY25ScFptRmpkQzkyWlhKemFXOXVQeUlzSUNKQmNtVWdiV2x6YzJsdVp5QmtaWEJsYm1SbGJtTnBaWE1zSUhOMFlXeGxJR1YyYVdSbGJtTmxJR0Z1WkNCMWJtdHViM2R1SUhKbGMzVnNkSE1nY0hKbGMyVnlkbVZrUHlJc0lDSkpjeUJ5ZFc1MGFXMWxJRzl3WlhKaGRHbHZiaUJqYUdWamEybHVaeTl5YjNWMGFXNW5JSEpoZEdobGNpQjBhR0Z1SUdOb2IyOXphVzVuSUhSaGMyc2daMjloYkhNZ2IzSWdjMlZ0WVc1MGFXTWdZMjl1WTJ4MWMybHZibk0vSWl3Z0lrUnZaWE1nY0dGcGNtVmtJSE4xWW5OMGNtRjBaU0JsZG1Gc2RXRjBhVzl1SUdSbGJXOXVjM1J5WVhSbElHRmpZMlZ3ZEdGaWJHVWdjWFZoYkdsMGVTQmhibVFnYkc5M1pYSWdkRzkwWVd3Z2QyOXlhejhpWFN3Z0ltOXlhV2RwYmlJNklDSjJNVjl3Y21WelpYSjJaV1FpTENBaWNtVmpiM0prWDNabGNuTnBiMjRpT2lBeUxDQWliR1ZuWVdONVgzSmxZMjl5WkY5MlpYSnphVzl1SWpvZ01Td2dJbXhsWjJGamVWOXdZWGxzYjJGa1gzTm9ZVEkxTmlJNklDSmpZakUzT1RVNFlXSTRPR015TVRrek5UYzVOREEyTjJWallqSXlNRFU1WkdRd1lUUTRNbVV4T0RReVpHRTBZV0UzTmpFMU1UUmhNREl4TmpBeE1XUXdJaXdnSW1SdmJXRnBibDlwWkNJNklDSkVNRElpTENBaVltOWtlVjlwWkNJNklDSkVNREl1UWpBeElpd2dJbk4xWW1aaGJXbHNlVjlwWkNJNklDSkdNREV1UVNJc0lDSnphV1JsWTJGeVgzSnZiR1VpT2lBaVkyaGxZMnRsY2w5dmNsOXlaV052Y21SZllYTmZjMk52Y0dWa0lpd2dJbk52ZFhKalpWOXlaWFpwWlhkZmMzUmhkSFZ6SWpvZ0ltNXZkRjl5WlhSeWFXVjJaV1JmYjNKZmNHRnpjMkZuWlY5MlpYSnBabWxsWkNJc0lDSjNjbUZ3Y0dWeVgzWmhiR2xrWVhScGIyNWZjM1JoZEhWeklqb2dJbTV2ZEY5MllXeHBaR0YwWldRaUxDQWlaWFpwWkdWdVkyVmZiR0Z1WlNJNklDSnNaV2RoWTNsZmNISnZZMlZ6YzE5eGRXRnlZVzUwYVc1bE
